server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always #??? ?? ???.

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update #create? ??? ????? ??? ??? ?? ??. update? ??.
    show-sql: true #??? jpa? create ??? sql? ??? ??? ? ??.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect #h2 ??? mysql ???? ???.