server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always #??? ?? ???.

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update #create? ??? ????? ??? ??? ?? ??. update? ??.
    show-sql: false #??? jpa? create ??? sql? ??? ??? ? ??.
    properties:
      hibernate:
        format_sql: true # SQL ???
        highlight_sql: true # SQL ?????
        use_sql_comments: true # SQL ?? ??

logging:
  level:
    org.hibernate.SQL: DEBUG # Hibernate? ??? SQL ??? ??? ?????. DEBUG ??? ?? ?? ????, ?? SQL ??? ??? ? ????.
    org.hibernate.orm.jdbc.bind: TRACE # JDBC ??? ???? ???? ??? ?????. TRACE ??? ?? ??? ??? ????, SQL ??? ????? ???? ?? ??? ? ????.
    org.hibernate.orm.jdbc.extract: TRACE # JDBC ?? ???? ???? ??? ?????. TRACE ??? ????????? ??? ???? ??? ??? ?????.
    org.springframework.transaction.interceptor: TRACE # ??? ???? ?? ???? ???? ??? ?????. TRACE ??? ???? ??, ??, ?? ?? ??? ??? ?????.
