server:
  port: 8080

spring:
  output:
    ansi:
      enabled: always # 콘솔에 ANSI 색상 출력 활성화

  profiles:
    active: dev

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update # 데이터베이스 스키마 자동 업데이트. 'create'는 매번 새로 생성, 'update'는 기존 스키마 유지
    show-sql: false # JPA가 생성한 SQL을 콘솔에 출력하지 않음
    properties:
      hibernate:
        format_sql: true # SQL 쿼리 포맷팅
        highlight_sql: true # SQL 쿼리 하이라이트
        use_sql_comments: true # SQL 쿼리에 주석 추가
        defualt_batch_fetch_size: 10 # 배치 처리 시 한 번에 가져올 데이터의 수

logging:
  level:
    org.hibernate.SQL: DEBUG # Hibernate가 실행한 SQL 쿼리 로깅. DEBUG 레벨에서만 출력
    org.hibernate.orm.jdbc.bind: TRACE # JDBC 바인딩 파라미터 로깅. TRACE 레벨에서만 출력
    org.hibernate.orm.jdbc.extract: TRACE # JDBC 결과 추출 로깅. TRACE 레벨에서만 출력
    org.springframework.transaction.interceptor: TRACE # 트랜잭션 관련 로깅. TRACE 레벨에서만 출력
